### ISSUE TITLE
Using later ENSEMBL Annotation GFF3

### ISSUE THREAD

**Issue by georgia-katsoula** [ConesaLab/tappAS#29] opened 2021-07-27 16:55 UTC
Hi Angeles,

Thank you for tappAS and the tutorials, very nice work!
I am working with bulk short-read RNA-seq which I have mapped to GRCh38.97 transcriptome using Salmon. I am trying to run FDA tappAS using a later Ensembl version .gff3 file but I get this error:
`[ERROR] java.nio.charset.MalformedInputException Code Exception: Input length = 1`

I downloaded the gff3 file from here. 
[http://ftp.ensembl.org/pub/release-97/gff3/homo_sapiens/Homo_sapiens.GRCh38.97.gff3.gz ] and added it in the create new project panel. 

Should I be doing something differently? 

* Extra quick question: Can covariates (e.g SVs) be included somehow in the DIU analysis? 

Best,
Georgia

**Comment by aarzalluz** [comment] 2021-07-28 09:54
Duplicate of #9.

**Comment by aarzalluz** [comment] 2021-07-28 09:55
Dear @georgia-katsoula,

Please see issue #9 for a detailed answer on the difference between reference database GFF3 files, and tappAS own GFF3 functional annotation. You'll find more info on how to create your own tappAS GFF3 annotation in that thread.

Best,

Ángeles

**Comment by georgia-katsoula** [comment] 2021-07-29 08:37
Dear Ángeles,

Thank you for the quick response. I do not have long read data and I am bit confused. I see that the input of the IsoAnnot Lite contains two files (classification.txt and junctions.txt) obtained from SQUANTI3 (which requires minimal input 
1)Long read-defined transcriptome 
2)Reference annotation in GTF format 
3)Reference genome. 
Should I be running SQUANTI3 (qc and rules filter)  to obtain these files? I am unsure what to provide in the  Long read-defined transcriptome in this case. 

Best,
Georgia

**Comment by aarzalluz** [comment] 2021-07-29 15:34
Dear @georgia-katsoula,

In your case, in which you are using a reference transcriptome from ENSEMBL, there are two possible options:

1. You could quantify isoform expression using the same human ENSEMBL transcriptome version that is available in tappAS, which is ENSEMBL 86. If you do this, you'll immediately have access to our built-in functional annotation (Human ENSEMBL, available directly upon tappAS creation).

2. Alternatively, you could annotate a newer ENSEMBL reference for human using SQ3 and IsoAnnotLite. In that case, you would indeed need to run SQ3 + IsoAnnotLite for that transcriptome, transferring annotations from our human ENSEMBL functional annotation GFF3 file (available through the tappAS website).

Personally, I would recommend the first, not only because it is simpler, but also because you'll be able to make use of the very comprehensive catalog of functional annotations that were added to ENSEMBL 86 isoform models. While transferring annotations with IsoAnnotLite is generally very accurate, it is inevitable that some functional labels are lost in the process. Going for **1** would maximize the richness of your functional analyses while losing a only some transcriptome information (novel isoforms/genes that may have been added to ENSEMBL, and other database updates).

I hope this helps!

Ángeles

**Comment by georgia-katsoula** [comment] 2021-07-29 17:32
Dear Ángeles,

Thank you for your proposal, unfortunately running the quantification again is not easy as I have a lot of samples and currently computational resources are limited. So I will give a try to the 2nd option although I do understand that the 1st would be better.

I have been trying to run the SQ3 quality control as follows:

`python SQANTI3/sqanti3_qc.py Desktop/tapas/Homo_sapiens.GRCh38.97.gtf Desktop/tapas/Homo_sapiens.GRCh38.97.gtf  Desktop/tapas/Homo_sapiens.GRCh38.97.cdna.all.fa  --gff3 Desktop/tapas/Homo_sapiens_GRCh38_Ensembl_86.gff3 --isoAnnotLite`

Long read-defined transcriptome : `Homo_sapiens.GRCh38.97.gtf` (as in my case I have no long read)
Reference annotation in GTF format:  `Homo_sapiens.GRCh38.97.gtf` (same)
Reference genome: `Homo_sapiens.GRCh38.97.cdna.all.fa`

with flags `--gff3`  GFF3 = `Homo_sapiens_GRCh38_Ensembl_86.gff3` (this is the one I dowloaded from tappAS repository)
`--isoAnnotLite` 

I get the error:
```
**** Running SQANTI3...
**** Parsing provided files....
Reading genome fasta /Users/georgia.katsoula/Desktop/tapas/Homo_sapiens.GRCh38.97.cdna.all.fa....
Traceback (most recent call last):
  File "/Users/georgia.katsoula/SQANTI3/sqanti3_qc.py", line 2500, in <module>
    main()
  File "/Users/georgia.katsoula/SQANTI3/sqanti3_qc.py", line 2483, in main
    run(args)
  File "/Users/georgia.katsoula/SQANTI3/sqanti3_qc.py", line 1872, in run
    genome_dict = dict((r.name, r) for r in SeqIO.parse(open(args.genome), 'fasta'))
  File "/Users/georgia.katsoula/SQANTI3/sqanti3_qc.py", line 1872, in <genexpr>
    genome_dict = dict((r.name, r) for r in SeqIO.parse(open(args.genome), 'fasta'))
  File "/Users/georgia.katsoula/anaconda3/envs/SQANTI3.env/lib/python3.9/site-packages/Bio/SeqIO/Interfaces.py", line 74, in __next__
    return next(self.records)
  File "/Users/georgia.katsoula/anaconda3/envs/SQANTI3.env/lib/python3.9/site-packages/Bio/SeqIO/FastaIO.py", line 198, in iterate
    for title, sequence in SimpleFastaParser(handle):
  File "/Users/georgia.katsoula/anaconda3/envs/SQANTI3.env/lib/python3.9/site-packages/Bio/SeqIO/FastaIO.py", line 47, in SimpleFastaParser
    for line in handle:
  File "/Users/georgia.katsoula/anaconda3/envs/SQANTI3.env/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
```

Is it because I specify the same .gtf in the Long read-defined transcriptome? 
What should I be providing in this case when I just want to transfer the labels from one version to the other with no LRS data? 

(If I provide less arguments (skipping the Long read defined transcriptome I get the error that the argument is missing).

Thank you for you help

Georgia

**Comment by aarzalluz** [comment] 2021-08-02 15:03
Hi @georgia-katsoula,

I am no SQANTI3 expert, but it seems from the error that there is a problem with the reference genome you provided. I believe that the *.dna.toplevel.fa* file does not correspond to the reference genome. About the difference between toplevel sequences and primary assemblies, see this from ENSEMBL's README:

> TOPLEVEL
> These files contains all sequence regions flagged as toplevel in an Ensembl schema. This includes chromsomes, regions not
> assembled into chromosomes and N padded haplotype/patch regions.

And:

> PRIMARY ASSEMBLY
> Primary assembly contains all toplevel sequence regions excluding haplotypes and patches. This file is best used for 
> performing sequence similarity searches where patch and haplotype sequences would confuse analysis.   

I would suggest trying the same run with *Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz* (decompressed before running SQ3) as your reference genome, to see if that solves the utf-8 error you're getting.

Mentioning @psalguerog (IsoAnnotLite developer+maintainer) to see if he spots anything else that might help solve your problem!


Ángeles

**Comment by aarzalluz** [comment] 2021-10-04 09:45
Closed and considered as solved (unless user reports that the issue persists).

**Closed by aarzalluz** 2021-10-04 09:45 UTC
Labels: duplicate
