### ISSUE TITLE
IsoAnnotLite annotation file

### ISSUE THREAD

**Issue by Ismail-Curie** [ConesaLab/tappAS#19] opened 2021-01-13 14:11 UTC
The annotated transcripts in the file created by IsoAnnotLite look like this,

PB.100.23	tappAS	gene	1	2828	.	-	.	ID=ENSG00000162408; Name=ENSG00000162408; Desc=ENSG00000162408; PosType=T
PB.100.23	tappAS	CDS	28	2136	.	-	.	ID=Protein_PB.100.23; Name=Protein_PB.100.23; Desc=Protein_PB.100.23; PosType=T

even if the correct information exists in tappas gff file.

Thank you for your help.

**Comment by aarzalluz** [comment] 2021-01-14 12:32
Hi @Ismail-Curie,

I'm not sure I understand your question, but I assume that it has to do with IsoAnnotLite not transferring functional information properly.

If so, a [new version of IsoAnnotLite](https://isoannot.tappas.org/isoannot-lite/) is now available in our website. Feel free to try it out and see if your annotation problems are solved after annotating your isoforms using the new script -we have been working on improving some of the issues that users have reported.

If so, do let us know! Feedback is really useful for us to keep our software up and running.

If this does not solve your problem, please give us some more information so that we can troubleshoot.

Best,


Ángeles

**Comment by Ismail-Curie** [comment] 2021-01-14 15:10
Hi @aarzalluz,

I tried the new version of IsoAnnotLite and I still have the same problem, 

I sent you my inputs and the output of IsoAnnotLite if you can take a look on what might cause the problem.

Thank you very much,
Ismail

**Comment by aarzalluz** [comment] 2021-01-14 15:16
Hi @Ismail-Curie,

I'm sorry -could you describe your problem with a little bit more detail? I'm can't quite grasp what's wrong just by looking at the print you pasted in the issue. 

Also, does this GFF3 give you an error when trying to load it into tappAS? If so, could you paste the section of the log where that error appears?

Once you give us some more information, I will send your files to my colleague @psalguerog and we'll see what we can do to help.

Best,
 
Ángeles

**Comment by Ismail-Curie** [comment] 2021-01-14 15:46
Hi @aarzalluz ,

There are no errors when loading the gff file to TappAs, it's just instead of getting the gene and protein name and the description of the gene, I get the Ensembl gene symbol or the transcript id, the annotation of the transcripts is available in the input gff file for IsoannotLite, but not in the output and I couldn't find why IsoAnnotLite doesn't properly transfer the functional information.

Thank you,
Ismail

**Comment by psalguerog** [comment] 2021-03-12 10:08
Hi @Ismail-Curie,

We were checking your problem and as you said, IsoAnnotLite is using the Gene and Protein ID as Name and Description. We will fix that minor error in future versions of IsoAnnotLite. Thank you for reporting.

Once the problem is solved, we will let you know in this issue.

Best,
Pedro Salguero

**Comment by aarzalluz** [comment] 2021-03-30 12:02
Hi @Ismail-Curie,

We recently released IsoAnnotLite v2.5, and took your suggestion into account. As a result, our algorithm now transfers the gene description field to the output GFF3 file. 

However, we have decided to refrain from transfering Protein IDs, given that it is not assured that proteins predicted by IsoAnnotLite will exactly match proteins included in reference databases, i.e. UniProt.

I hope the improvements will be useful to you! I'm closing the issue, but do not hesitate to open a new one if you have any more questions.

Best,


Ángeles

**Closed by aarzalluz** 2021-03-30 12:02 UTC
